### ISSUE TITLE
error when pressing PageDown for a package with few entries 

### ISSUE THREAD

**Issue by rfourquet** [GunnarFarneback/PackageCompatUI.jl#15]
Upon calling `compat_ui()`, there is a terminal menu of a certain height appearing. If the number of entries for a given package has fewer entries than this height, then an error happens, e.g.: 
```
Bits:
 > [ ] 0.1.0               2018-09-03
ERROR: BoundsError: attempt to access 2-element Vector{String} at index [-17]
Stacktrace:
 [1] getindex
   @ ./array.jl:924 [inlined]
 [2] writeline(buf::IOBuffer, menu::PackageCompatUI.Menu, idx::Int64, iscursor::Bool)
   @ PackageCompatUI ~/.julia/packages/PackageCompatUI/YMbd3/src/menu.jl:172
[...]
```
And by the way, thanks for this great package!

**Comment by rfourquet** [comment]
Yes I was very surprised that this was not already reported... but I can reproduce this on two linux computers, with julia 1.8. To reproduce, it's enough that I initialize a project containing two packages: `PackageCompatUI` and `Bits`. Call `compat_ui()` in this project, three red entries appear in a menu: these two packages plus "julia", go to the Bits entry (downkey then rightkey), and then pagedown key produces the error above.

**Comment by GunnarFarneback** [comment]
I'm on Linux but cannot reproduce the problem. To make it state independent I'm running the following commands in the shell:
```
mkdir /tmp/testdepot
JULIA_DEPOT_PATH=/tmp/testdepot julia -e 'using Pkg; Pkg.add(["PackageCompatUI", "Bits"])'
JULIA_DEPOT_PATH=/tmp/testdepot julia -e 'using PackageCompatUI; compat_ui()'
```
then I press downkey, rightkey, downkey and get the following output with no error:
```
loading data for PackageCompatUI                                             
Cloning the General Registry. This might take some time.
Cloning into bare repository '.'...
remote: Enumerating objects: 657321, done.
remote: Counting objects: 100% (145/145), done.
remote: Compressing objects: 100% (114/114), done.
remote: Total 657321 (delta 38), reused 117 (delta 31), pack-reused 657176
Receiving objects: 100% (657321/657321), 203.79 MiB | 22.51 MiB/s, done.
Resolving deltas: 100% (354819/354819), done.

Bits: 
   [ ] 0.1.0               2018-09-03
 > [ ] 0.2.0               2019-05-11
```
Does this example crash for you?

If it does, I suspect it's necessary to start comparing terminals and terminal settings.

**Comment by rfourquet** [comment]
Thank you for your answer, so yes it still crashes with these commands settig `JULIA_DEPOT_PATH`. But note:

> then I press downkey, rightkey, downkey and get the following output with no error:

The third key which makes it crash for me is pagedown-key, not down-key.

**Comment by GunnarFarneback** [comment]
Ah, thanks for pointing out that my reading is deficient. Now I can reproduce the crash, which means that I can fix it.

**Comment by GunnarFarneback** [comment]
Turns out to be an upstream bug in `TerminalMenus`. I'll see if I can also work around the bug.
