### ISSUE TITLE
Fetch fails on registries without master branch

### ISSUE THREAD

**Issue by pbouffard** [GunnarFarneback/PackageCompatUI.jl#18]
I work with a private registry whose main branch is `main` and not `master` like the General registry. PackageCompatUI has `master` hardcoded in the `find_version_dates!` method and so `compat_ui()` ends up failing on this registry with the error `fatal: couldn't find remote ref master`.

I looked around a bit hoping to find some nice canonical way of determining the name of the main branch of a Git repo (unfortunate overloading of terminology here..) but so far nothing has worked, perhaps because of the particular way the registries are cloned. But it looks like including `"master:master"` in the `fetch` command isn't needed anyway so the fix might just be to remove it altogether.

**Comment by GunnarFarneback** [comment]
Since the clone is a bare repo, it's necessary to include `master:master` or `main:main`. Please check if #19 works for you.
